import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Parkirin',
  description: 'Generated by create next app',
}

export default function DashboardLayout({ children }) {
  return (
    <html lang="id">
      <body className={`${inter.className} text-slate-900`}>
        {children}
      </body>
    </html>
  )
}
